In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_sub = pd.read_csv('sample_submission.csv')

In [3]:
sample_sub.head()

date_time  traffic_volume
0  1969-05-17 21:00:00             500
1  1969-05-17 21:00:00             530
2  1969-05-17 21:00:00             545
3  1969-05-17 22:00:00             750

In [4]:
df = pd.read_csv('Train.csv')

In [5]:
df.head(10)

date_time is_holiday  air_pollution_index  humidity  wind_speed  \
0  2012-10-02 09:00:00       None                  121        89           2   
1  2012-10-02 10:00:00       None                  178        67           3   
2  2012-10-02 11:00:00       None                  113        66           3   
3  2012-10-02 12:00:00       None                   20        66           3   
4  2012-10-02 13:00:00       None                  281        65           3   
5  2012-10-02 14:00:00       None                   23        65           3   
6  2012-10-02 15:00:00       None                  184        64           3   
7  2012-10-02 16:00:00       None                  167        64           3   
8  2012-10-02 17:00:00       None                  119        63           3   
9  2012-10-02 18:00:00       None                  161        63           3   

   wind_direction  visibility_in_miles  dew_point  temperature  rain_p_h  \
0             329                    1          1       288.28       0.0   
1             330                    1          1       289.36       0.0   
2             329                    2          2       289.58       0.0   
3             329                    5          5       290.13       0.0   
4             329                    7          7       291.14       0.0   
5             328                    6          6       291.72       0.0   
6             328                    7          7       293.17       0.0   
7             327                    7          7       293.86       0.0   
8             327                    6          6       294.14       0.0   
9             326                    3          3       293.10       0.0   

   snow_p_h  clouds_all weather_type weather_description  traffic_volume  
0       0.0          40       Clouds    scattered clouds            5545  
1       0.0          75       Clouds       broken clouds            4516  
2       0.0          90       Clouds     overcast clouds            4767  
3       0.0          90       Clouds     overcast clouds            5026  
4       0.0          75       Clouds       broken clouds            4918  
5       0.0           1        Clear        sky is clear            5181  
6       0.0           1        Clear        sky is clear            5584  
7       0.0           1        Clear        sky is clear            6015  
8       0.0          20       Clouds          few clouds            5791  
9       0.0          20       Clouds          few clouds            4770

In [6]:
df.shape

(33750, 15)

In [7]:
df['weather_type'].unique()

array(['Clouds', 'Clear', 'Rain', 'Drizzle', 'Mist', 'Haze', 'Fog',
       'Thunderstorm', 'Snow', 'Squall', 'Smoke'], dtype=object)

In [8]:
df['clouds_all'].unique()

array([ 40,  75,  90,   1,  20,   0, 100,  92,  99,  81,  50,  72,  56,
        57,  93,  85,  68,  87,  91,  96,  48,  60,   8,  38,  46,  98,
        86,  16,   6,  59,  54,  89,  78,  36,  17,  58,  63,  42,  25,
        11,  13,  83,  70,  84,   3,  77,  88,  67,  97,  62,  32,   4,
         5,   2,  44,  24,  76,  64,  80,  12])

In [9]:
df['humidity'].unique()

array([ 89,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,  57,  56,
        55,  48,  42,  33,  30,  32,  37,  36,  39,  41,  44,  47,  50,
        75,  70,  93,  84,  53,  49,  45,  28,  26,  34,  54,  71,  76,
        35,  27,  25,  23,  24,  31,  52,  69,  80,  74,  38,  51,  79,
        21,  43,  68,  87,  86,  29,  40,  92,  19,  18,  20,  81, 100,
        46,  83,  85,  88,  90,  95,  97,  91,  78,  82,  72,  77,  73,
        94,  96,  98,  17,  22,  99,  15,  16,  14,  13])

In [10]:
df['wind_speed'].unique()

array([ 2,  3,  4,  5,  7,  6,  0,  1,  9,  8, 10, 12, 11, 13, 15, 14, 16])

In [11]:
df['year'] = pd.DatetimeIndex(df['date_time']).year

In [12]:
df['month'] = pd.DatetimeIndex(df['date_time']).month

In [ ]:
df.describe()

In [13]:
df['is_holiday'].unique()

array(['None', 'Columbus Day', 'Veterans Day', 'Thanksgiving Day',
       'Christmas Day', 'New Years Day', 'Washingtons Birthday',
       'Memorial Day', 'Independence Day', 'State Fair', 'Labor Day',
       'Martin Luther King Jr Day'], dtype=object)

In [18]:
mapping = {'None':0, 'Columbus Day':1, 'Veterans Day':2, 'Thanksgiving Day':3,
       'Christmas Day':4, 'New Years Day':5, 'Washingtons Birthday':6,
       'Memorial Day':7, 'Independence Day':8, 'State Fair':9, 'Labor Day':10,
       'Martin Luther King Jr Day':11}
x_train.replace({'is_holiday': mapping})

is_holiday  air_pollution_index  humidity  wind_speed  wind_direction  \
0               0                  121        89           2             329   
1               0                  178        67           3             330   
2               0                  113        66           3             329   
3               0                   20        66           3             329   
4               0                  281        65           3             329   
...           ...                  ...       ...         ...             ...   
33745           0                   74        85           1             328   
33746           0                   81        70           1              24   
33747           0                  138        70           1              24   
33748           0                  229        66           1              42   
33749           0                  140        63           1              27   

       visibility_in_miles  dew_point  temperature  rain_p_h  snow_p_h  \
0                        1          1       288.28       0.0       0.0   
1                        1          1       289.36       0.0       0.0   
2                        2          2       289.58       0.0       0.0   
3                        5          5       290.13       0.0       0.0   
4                        7          7       291.14       0.0       0.0   
...                    ...        ...          ...       ...       ...   
33745                    7          7       287.88       0.0       0.0   
33746                    2          2       286.95       0.0       0.0   
33747                    1          1       286.95       0.0       0.0   
33748                    6          6       285.75       0.0       0.0   
33749                    8          8       285.75       0.0       0.0   

       clouds_all weather_type  year  month  
0              40       Clouds  2012     10  
1              75       Clouds  2012     10  
2              90       Clouds  2012     10  
3              90       Clouds  2012     10  
4              75       Clouds  2012     10  
...           ...          ...   ...    ...  
33745          90         Mist  2017      5  
33746          90         Rain  2017      5  
33747          90         Mist  2017      5  
33748          90         Rain  2017      5  
33749          90         Mist  2017      5  

[33750 rows x 14 columns]

In [15]:
x_train = df
y_train = df['traffic_volume']

In [16]:
x_train = x_train.drop(['traffic_volume','weather_description','date_time'],axis=1)

In [17]:
x_train

is_holiday  air_pollution_index  humidity  wind_speed  wind_direction  \
0           None                  121        89           2             329   
1           None                  178        67           3             330   
2           None                  113        66           3             329   
3           None                   20        66           3             329   
4           None                  281        65           3             329   
...          ...                  ...       ...         ...             ...   
33745       None                   74        85           1             328   
33746       None                   81        70           1              24   
33747       None                  138        70           1              24   
33748       None                  229        66           1              42   
33749       None                  140        63           1              27   

       visibility_in_miles  dew_point  temperature  rain_p_h  snow_p_h  \
0                        1          1       288.28       0.0       0.0   
1                        1          1       289.36       0.0       0.0   
2                        2          2       289.58       0.0       0.0   
3                        5          5       290.13       0.0       0.0   
4                        7          7       291.14       0.0       0.0   
...                    ...        ...          ...       ...       ...   
33745                    7          7       287.88       0.0       0.0   
33746                    2          2       286.95       0.0       0.0   
33747                    1          1       286.95       0.0       0.0   
33748                    6          6       285.75       0.0       0.0   
33749                    8          8       285.75       0.0       0.0   

       clouds_all weather_type  year  month  
0              40       Clouds  2012     10  
1              75       Clouds  2012     10  
2              90       Clouds  2012     10  
3              90       Clouds  2012     10  
4              75       Clouds  2012     10  
...           ...          ...   ...    ...  
33745          90         Mist  2017      5  
33746          90         Rain  2017      5  
33747          90         Mist  2017      5  
33748          90         Rain  2017      5  
33749          90         Mist  2017      5  

[33750 rows x 14 columns]

# Training using Linear Regression





In [ ]:
from sklearn.ensemble import RandomForestRegressor



In [ ]:
model = RandomForestRegressor()

In [ ]:
model.fit(x_train, y_train)

In [ ]:
model.score(x_train, y_train)

In [ ]:
x_test = pd.read_csv('Test.csv')

In [ ]:
x_test = x_test.drop(['is_holiday', 'weather_type', 'weather_description','date_time'],axis=1)

In [ ]:
x_test

In [ ]:
output = model.predict(x_test)

In [ ]:
import requests

In [ ]:
payload = {'key1': 'value1', 'key2': 'value2'}

r = requests.post("https://httpbin.org/post", data=payload)
print(r.text)